name: autonomy_flutter
description: Autonomy cross platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.22.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  web3dart: ^2.3.3
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.0
  get_it: ^7.2.0
  permission_handler: ^8.1.6
  qr_code_scanner: ^0.6.1
  uuid: ^3.0.5
  http: ^0.13.2
  retrofit:
  dio: ^4.0.4
  qr_flutter: ^4.0.0
  share: ^2.0.4
  flutter_svg: ^1.0.0
  aws_firehose_api: ^1.2.0
  aws_cognito_identity_api: ^1.2.0
  tezart:
    git: https://github.com/autonomy-system/tezart.git
  local_auth: ^1.1.10
  sentry_flutter: ^6.2.2
  video_player: ^2.2.19
  webview_flutter: ^3.0.0
  shake: ^2.0.0
  uni_links: ^0.5.1
  floor: ^1.2.0
  flutter_email_sender: ^5.1.0
  logging: ^1.0.2
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  device_info_plus: ^3.2.1
  package_info_plus: ^1.4.0
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.2.0
  in_app_purchase: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  flutter_native_splash: ^2.0.5
  html_unescape: ^2.0.0
  flutter_fgbg: ^0.1.0
  libauk_dart:
    git:
      url: https://github.com/autonomy-system/libauk-dart.git
      ref: main
  wallet_connect:
    git: https://github.com/autonomy-system/wallet-connect-dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  build_runner:
  built_value_generator:
  json_serializable:
  floor_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/penrose.png
    - assets/images/penrose_onboarding.png
    - assets/images/iconQr.svg
    - assets/images/iconEth.svg
    - assets/images/iconUsd.svg
    - assets/images/iconXtz.svg
    - assets/images/iconBitmark.svg
    - assets/images/iconClose.svg
    - assets/images/iconForward.svg
    - assets/images/cil_external-link.svg
    - assets/images/tezos_social_icon.svg
    - assets/images/feralfileAppIcon.svg
    - assets/images/autonomyIcon.png
    - assets/images/rainbow.png
    - assets/images/trust-alternative.png
    - assets/images/metamask-alternative.png
    - assets/images/walletconnect-alternative.png
    - assets/images/kukai_wallet.png
    - assets/images/tezos_wallet.png
    - assets/images/premium_comparation.svg
    - assets/images/face_id.svg
    - assets/images/touch_id.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AtlasGrotesk
      fonts:
        - asset: fonts/AtlasGrotesk/AtlasGrotesk-Regular.otf
        - asset: fonts/AtlasGrotesk/AtlasGrotesk-Bold.otf
          weight: 700
    - family: DomaineSansText
      fonts:
        - asset: fonts/DomaineSansText/DomaineSansText-Regular.otf
    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono/IBMPlexMono-Regular.ttf
        - asset: fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
          weight: 700
