name: Deploy the android app
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 2.10.3'
          channel: stable
      - run: flutter pub get
      - run: flutter build apk
      - name: upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: support-zzd0-28/Autonomy-Android-1
          token: ${{ secrets.APPCENTER_API_TOKEN }}
          group: Collaborators
          file: build/app/outputs/flutter-apk/app-release.apk
          notifyTesters: false
          debug: false
