name: Deploy the android app
on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 2.10.3'
          channel: stable
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
#      - name: upload artefact to App Center
#        uses: wzieba/AppCenter-Github-Action@v1
#        with:
#          appName: wzieba/Sample-App
#          token: ${{secrets.APP_CENTER_TOKEN}}
#          group: Testers
#          file: app/build/outputs/apk/release/app-release-unsigned.apk
#          notifyTesters: true
#          debug: false
