name: Deploy the iOS app
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        type: choice
        description: 'Fastlane lane to use'
        required: true
        options:
        - ciappcenter
        - citestflight
        default: 'ciappcenter'
      version:
          description: 'App version'
          required: true 

  push:
    tags:
    - '*'

jobs:
  fastlane-deploy:
    runs-on: macOS-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: master
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: ios

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KEY_VAULT_DEPLOYMENT_KEY }}

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_INDEXER_MAINNET_API_URL: ${{ secrets.INDEXER_MAINNET_API_URL }}
          envkey_INDEXER_TESTNET_API_URL: ${{ secrets.INDEXER_TESTNET_API_URL }}
          envkey_WEB3_RPC_MAINNET_URL: ${{ secrets.WEB3_RPC_MAINNET_URL }}
          envkey_WEB3_RPC_TESTNET_URL: ${{ secrets.WEB3_RPC_TESTNET_URL }}
          envkey_TEZOS_NODE_CLIENT_MAINNET_URL: ${{ secrets.TEZOS_NODE_CLIENT_MAINNET_URL }}
          envkey_TEZOS_NODE_CLIENT_TESTNET_URL: ${{ secrets.TEZOS_NODE_CLIENT_TESTNET_URL }}
          envkey_BITMARK_API_MAINNET_URL: ${{ secrets.BITMARK_API_MAINNET_URL }}
          envkey_BITMARK_API_TESTNET_URL: ${{ secrets.BITMARK_API_TESTNET_URL }}
          envkey_FERAL_FILE_API_MAINNET_URL: ${{ secrets.FERAL_FILE_API_MAINNET_URL }}
          envkey_FERAL_FILE_API_TESTNET_URL: ${{ secrets.FERAL_FILE_API_TESTNET_URL }}
          envkey_EXTENSION_SUPPORT_MAINNET_URL: ${{ secrets.EXTENSION_SUPPORT_MAINNET_URL }}
          envkey_EXTENSION_SUPPORT_TESTNET_URL: ${{ secrets.EXTENSION_SUPPORT_TESTNET_URL }}
          envkey_CONNECT_WEBSOCKET_MAINNET_URL: ${{ secrets.CONNECT_WEBSOCKET_MAINNET_URL }}
          envkey_CONNECT_WEBSOCKET_TESTNET_URL: ${{ secrets.CONNECT_WEBSOCKET_TESTNET_URL }}
          envkey_AUTONOMY_AUTH_URL: ${{ secrets.AUTONOMY_AUTH_DEV_URL }}
          envkey_CUSTOMER_SUPPORT_URL: ${{ secrets.CUSTOMER_SUPPORT_DEV_URL }}
          envkey_CURRENCY_EXCHANGE_URL: ${{ secrets.CURRENCY_EXCHANGE_URL }}
          envkey_AUTONOMY_PUBDOC_URL: ${{ secrets.AUTONOMY_PUBDOC_URL }}
          envkey_FERAL_FILE_AUTHORIZATION_PREFIX: ${{ secrets.FERAL_FILE_AUTHORIZATION_PREFIX }}
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          envkey_ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_DEV_APP_ID }}
          file_name: .env

      - run: flutter pub get

      # Build and deploy with Fastlane (by default, to ciappcenter track) 🚀.
      - name: Build and deploy with Fastlane
        env:
          ENTERPRISE_CERTIFICATE_PASSWORD: ${{ secrets.ENTERPRISE_CERTIFICATE_PASSWORD }}
          APPSTORE_CERTIFICATE_PASSWORD: ${{ secrets.APPSTORE_CERTIFICATE_PASSWORD }}
          JSON_FILE: ${{ secrets.JSON_FILE }}
          SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
          APP_VERSION: ${{ github.event.inputs.version }}

        run: |
          git clone git@github.com:bitmark-inc/mobile-signing-key-vault.git --depth 1
          echo $JSON_FILE >> key.json
          bundle exec fastlane install_plugins
          echo "APP_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          bundle exec fastlane ${{ github.event.inputs.lane || 'ciappcenter' }}
        
        working-directory: ios